# spring.profiles.active=dev

spring.application.name=backend
server.port=8036

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=kang
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 브라우저에서 접근할 URL 패턴
# spring.mvc.static-path-pattern=/**
spring.mvc.static-path-pattern=/**

# 실제 이미지가 저장된 물리적 경로 (마지막에 / 필수)
# spring.web.resources.static-locations=file:classpath:/static/
spring.web.resources.static-locations=file:./upload/, classpath:/static/

# Security 설정
spring.security.user.name=admin
spring.security.user.password=1234