spring.application.name=backend
server.port=${SERVER_PORT:8036}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:kang}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=file:./upload/, classpath:/static/

# Security
spring.security.user.name=${SPRING_SECURITY_USER:admin}
spring.security.user.password=${SPRING_SECURITY_PASSWORD:1234}

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3036,http://localhost:3000,https://kang.newlecture.com}
